spring.application.name=lms
# ==================================
# SERVER CONFIGURATION
# ==================================
server.port=8080
server.servlet.context-path=/

# ==================================
# DATABASE CONFIGURATION (PostgreSQL)
# ==================================
# Badilisha 'library_db' kulingana na jina la database uliyoitengeneza kwenye PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
# Weka username na password za PostgreSQL yako (kwa kawaida username ni postgres)
spring.datasource.username=postgres
spring.datasource.password=mmccky12
spring.datasource.driver-class-name=org.postgresql.Driver

# ==================================
# JPA / HIBERNATE CONFIGURATION
# ==================================
# 'update' inatengeneza au kubadilisha misingi ya meza (tables) bila kufuta data
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==================================
# JWT CONFIGURATION (Kama unatumia Security/JWT)
# ==================================
app.jwt.secret=MySecretKeyForLibraryManagementSystem128BitKey
app.jwt.expiration-ms=86400000